bases:
  - ../../base

namePrefix: "stg-"
nameSuffix: "-001"
commonLabels:
  stg: dev-app

patches:
  - ./patches/deployment.yml
  - ./patches/external-secret.yml

secretGenerator:
  - name: gcpsm-secret
    files:
      - secret-access-credentials=./service_account.json
