bases:
  - ../../base

resources:
  - ./managed-cert.yml
  - ./ingress.yml

namePrefix: "stg-"
nameSuffix: "-001"
commonLabels:
  stg: dev-app

patches:
  - ./patches/deployment.yml
  - ./patches/external-secret.yml
