apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    gcpsm:
      projectID: cloud-learn-dev
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: stg-gcpsm-secret-001-g42h2t64dh

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: stg-secretstore-001 # SecretStoreのmetadata.name

  target:
    name: stg-secrets

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: staging-dev-app_DATABASE_URL

    - secretKey: DEBUG
      remoteRef:
        key: staging-dev-app_DEBUG

    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: staging-dev-app_DJANGO_SECRET_KEY

    - secretKey: DJANGO_SETTINGS_MODULE
      remoteRef:
        key: staging-dev-app_DJANGO_SETTINGS_MODULE

    - secretKey: DJANGO_ALLOWED_HOSTS
      remoteRef:
        key: staging-dev-app_DJANGO_ALLOWED_HOSTS
