apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    gcpsm:
      projectID: cloud-learn-dev
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: overlaysごとに書き換え
            key: secret-access-credentials

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: secretstore

  target:
    name: overlaysごとに書き換え
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: overlaysごとに書き換え（Secret Manager上の名前を指定）
        version: latest

    - secretKey: DEBUG
      remoteRef:
        key: overlaysごとに書き換え（Secret Manager上の名前を指定）
        version: latest

    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: overlaysごとに書き換え（Secret Manager上の名前を指定）
        version: latest

    - secretKey: DJANGO_SETTINGS_MODULE
      remoteRef:
        key: overlaysごとに書き換え（Secret Manager上の名前を指定）
        version: latest

    - secretKey: DJANGO_ALLOWED_HOSTS
      remoteRef:
        key: overlaysごとに書き換え（Secret Manager上の名前を指定）
        version: latest
