name: GitHub Actions

on:
  repository_dispatch:
    types:
      - update-yml

jobs:
  update-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env
        run: |
          echo GITHUB_REF"=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo GITHUB_SHA"=${{ github.event.client_payload.github_sha }}" >> $GITHUB_ENV

      - name: Update staging yml
        if: ${{ env.GITHUB_REF }} == 'master'
        uses: mikefarah/yq@master
        with:
          cmd: IMAGE_TAG=' asia-northeast1-docker.pkg.dev/cloud-learn-dev/dev-app-img-repository/sample-image:${{ env.GITHUB_SHA }}' yq eval '.spec.template.spec.containers[0].image = env(IMAGE_TAG)' -i overlays/staging/patches/deployment.yml

      - name: Open merge request
        id: omr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/release/${{ env.GITHUB_SHA }}
          base: master
          delete-branch: true
          title: |
            [${{ env.GITHUB_SHA }}] Update Container Image
          body: |
            [${{ env.GITHUB_SHA }}] Update Container Image
            - Updated container image
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
            ${{ env.GITHUB_SHA }} release
          assignees: butterthon
          draft: false

      - name: Open merge request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.omr.outputs.pull-request-url }} --merge
